### ISSUE TITLE
README: Add erofs-utils.x86_64 as dependency

### ISSUE THREAD

**Issue by kastl-ars** [travier/fedora-sysexts#1]
Hi Timothée Ravier,

thanks for the nice repo, I had to try this out.

One thing I noticed when building as root on a Fedora40 vagrant VM is that erofs-utils is required, but not mentioned in the README.

Other than that it seemed to work flawlessly (I built the semanage sysext and used it on the same machine).

(I disabled the reset-selinux-labels step for now, as it seem to have hardcoded /run/host/ paths in it, need to take a closer look)

Have a nice day!

Kind Regards,
Johannes

**Comment by travier** [comment]
Thanks for the feedback. I've pushed an update that should clarify this.

**Comment by kastl-ars** [comment]
Thanks a lot, looks good! Have a nice day!
