### ISSUE TITLE
Title of images doesn't match `extension-release.d` name

### ISSUE THREAD

**Issue by AlexNPavel** [travier/fedora-sysexts#16]
I was trying to get an image here running on my Kinoite 41 (or more specifically Aurora-DX) machine and was running into issues. After some investigation, the issue seems to be that `systemd-sysext` expects the name of the image file (minus the file extension) to make the suffix of the `extension-release` file in the image. Currently, the names of the images contain the version and architecture of the image in the name, but the `extension.release` file does not. I was able to fix the issue either by renaming the file to `{{name}}.raw` or by making the following change to the `sysext.just` file:

```
--- a/sysext.just
+++ b/sysext.just
@@ -44,7 +44,7 @@ default:
     echo "{{base_images}}"
 
 # Main recipe with all the steps to use to build a sysext
-build target: (check target) clean (download-rpms target) download-manual setup-rootfs install-rpms install-files install-manual move-etc rm-ignored (reset-selinux-labels target) (build-erofs target)
+build target: (check target) clean (download-rpms target) download-manual (setup-rootfs target) install-rpms install-files install-manual move-etc rm-ignored (reset-selinux-labels target) (build-erofs target)
 
 # List the supported targets for this sysext. To use in CI and scripting
 targets:
@@ -160,7 +160,7 @@ download-manual:
     exit 0
 
 # Sets up the rootfs directory and creates the extension release config
-setup-rootfs:
+setup-rootfs target:
     #!/bin/bash
     set -euo pipefail
     # set -x
@@ -176,7 +176,12 @@ setup-rootfs:
 
     echo "➡️  Setting up extension config file"
     ${SUDO} install -d -m0755 usr/lib/extension-release.d
-    echo "ID=\"_any\"" | ${SUDO} tee usr/lib/extension-release.d/extension-release.{{name}} > /dev/null
+    version=$(podman run --rm -ti \
+        --security-opt label=disable \
+        "{{target}}" \
+        bash -c 'source /etc/os-release ; echo -n ${OSTREE_VERSION}')
+    arch=$(uname -m | sed 's/_/-/g')
+    echo "ID=\"_any\"" | ${SUDO} tee usr/lib/extension-release.d/extension-release.{{name}}-${version}-${arch} > /dev/null
```

The instructions currently say to do `sudo install -m 644 -o 0 -g 0 ${SYSEXT}/${SYSEXT}*.raw -t /var/lib/extensions/`, which won't work due to the incorrect naming, so either the instructions need to be updated to have `sudo install -m 644 -o 0 -g 0 ${SYSEXT}/${SYSEXT}*.raw -t /var/lib/extensions/${SYSEXT}.raw` and thus have the correct filename, or the repo needs the diff I posted above to change the `extension-release` name.

**Comment by travier** [comment]
Ah indeed, I have work in progress systemd-sysupdate instructions and the changes I pushed broke the defaults. Let's strip the version & arch from the name for now.

**Comment by travier** [comment]
Thanks!
