### ISSUE TITLE
How do I get the docker-ce sysext to work?

### ISSUE THREAD

**Issue by kekkoudesu** [travier/fedora-sysexts#53]
I'm using Fedora Kinoite 41.

```
Deployments:
● fedora:fedora/41/x86_64/kinoite
                  Version: 41.20241217.0 (2024-12-17T01:01:13Z)
                   Commit: b8db61312998dc6cf0be3e421f79ae5964dc449de290b17d73b94237d13d433d
             GPGSignature: Valid signature by 466CF2D8B60BC3057AA9453ED0622462E99D6AD1
```

I've got a script that does this:

```
#!/bin/bash

SYSEXT="docker-ce"
RELEASE_TAG="fedora-kinoite-41"
URL="https://github.com/travier/fedora-sysexts/releases/download/${RELEASE_TAG}/${SYSEXT}.conf"
curl --silent --location "${URL}" | sudo tee "/etc/sysupdate.d/${SYSEXT}.conf"
sudo /usr/lib/systemd/systemd-sysupdate list
sudo /usr/lib/systemd/systemd-sysupdate update
sudo systemctl restart systemd-sysext.service
systemd-sysext status
```

Which I ran after doing the `rpm-ostree update`. I've used `sudo systemctl restart systemd-sysext.service` but when I run:

```
systemd-sysext status
```

It tells me:

```
HIERARCHY EXTENSIONS SINCE
/opt      none       -    
/usr      none       -    
```

When I run:

```
sudo systemctl status systemd-sysext
● systemd-sysext.service - Merge System Extension Images into /usr/ and /opt/
     Loaded: loaded (/usr/lib/systemd/system/systemd-sysext.service; enabled; preset: enabled)
    Drop-In: /usr/lib/systemd/system/service.d
             └─10-timeout-abort.conf, 50-keep-warm.conf
     Active: active (exited) since Tue 2024-12-17 21:06:32 AEDT; 2min 47s ago
 Invocation: 9bda17f244da474a9c592411bee938d6
       Docs: man:systemd-sysext.service(8)
    Process: 4112 ExecStart=systemd-sysext refresh (code=exited, status=0/SUCCESS)
   Main PID: 4112 (code=exited, status=0/SUCCESS)
   Mem peak: 3.6M
        CPU: 37ms

Dec 17 21:06:31 fedora systemd[1]: Starting systemd-sysext.service - Merge System Extension Images into /usr/ and /opt/...
Dec 17 21:06:32 fedora (sd-merge)[4116]: No suitable extensions found (1 ignored due to incompatible image(s)).
Dec 17 21:06:32 fedora systemd[1]: Finished systemd-sysext.service - Merge System Extension Images into /usr/ and /opt/.
```

It seems like the extension is incompatible for some reason..? Not sure what I'm doing wrong.

**Comment by travier** [comment]
Sorry, I merged a bug yesterday and only fixed it today with https://github.com/travier/fedora-sysexts/commit/dc4687d63f4b03aa9d1ef5b7f1a022b12dec9397. Can you try it again with the extensions from the latest release? Thanks

**Comment by kekkoudesu** [comment]
What awful timing for all extensions to break :)

Thanks for fixing it so quickly! I tried updating with my `sysgrade.bash` script (I should really figure out Topgrade someday...) and the extension is there and working. Though, I found I needed to `groupadd docker` before it would work.

I guess as a side-effect of these being indirect layers separate from the host system, the post-installation scripts (scriptlets?) don't run to set the things up the package needs to run.

But hey, it works now!

**Comment by kekkoudesu** [comment]
Oh, and since there isn't a discussion tab or anything, I'll just ask it here...

When the README says "I recommend updating them at the same time as you update your system with bootc/rpm-ostree so that the content of the sysexts matches what is on your base system as right now there are no guarantees there."

does that mean the base system might break? Or that the extension might break? Or both? I can see Neovim not working for some reason, but if I failed to update Neovim at the same time, would that break the base system somehow?

**Comment by travier** [comment]
> Though, I found I needed to `groupadd docker` before it would work.

Ah, indeed. I've added a draft note for this in https://github.com/travier/fedora-sysexts/pull/55, but not tested it.

> I guess as a side-effect of these being indirect layers separate from the host system, the post-installation scripts (scriptlets?) don't run to set the things up the package needs to run.

Yes, that's it. We don't setup users/groups right now but we could change that and set them statically using systemd's JSON users records: https://systemd.io/USER_RECORD/

> Oh, and since there isn't a discussion tab or anything, I'll just ask it here...

Thanks for the suggestion. I've opened the discussion space.

> When the README says "I recommend updating them at the same time as you update your system with bootc/rpm-ostree so that the content of the sysexts matches what is on your base system as right now there are no guarantees there."
> 
> does that mean the base system might break? Or that the extension might break? Or both? I can see Neovim not working for some reason, but if I failed to update Neovim at the same time, would that break the base system somehow?

Theoretically, any bad extension could break the entire system as it may overlay a broken bash executable for example.

In practice, I think it's unlikely that incompatibilities would happen during a major Fedora release lifetime but it could happen. As most sysexts only extend the system and do not replace files, this would mean that neovim does not work but the rest of the system works for example.

**Comment by travier** [comment]
I created https://github.com/travier/fedora-sysexts/discussions/56 for the safety discussion
